import fs from 'fs';
import path from 'path';
import { exec } from '@actions/exec';
import { Config } from 'eslint-remote-tester/dist/exports-for-compare-action';

import {
    requirePeerDependency,
    ESLINT_REMOTE_TESTER_BIN,
} from './peer-dependencies';

const INTERNAL_CONFIG = 'eslint-remote-tester-compare-internal.config.js';
export const RESULTS_TMP = '/tmp/results.json';

/**
 * Configuration values used internally. These are overwritten from user provided configuration
 */
const DEFAULT_CONFIG: Partial<Config> = {
    cache: false,
};

// prettier-ignore
const CONFIGURATION_TEMPLATE = (
    configuration: Config,
    configurationPath: string
) =>
 `// Generated by eslint-remote-tester-run-action
const fs = require('fs');

module.exports = {
    ...${JSON.stringify(configuration, null, 4)},
    onComplete: async function onComplete(results, comparisonResults) {
        fs.writeFileSync('${RESULTS_TMP}', JSON.stringify(results || []));

        // User provided onComplete is injected here if present
        ${configuration.onComplete
            ? `await require('${configurationPath}').onComplete(results, comparisonResults);`
            : '// No onComplete detected'
        }
    }
};
`;

/**
 * Run `eslint-remote-tester` and save results to temporary location
 */
export default async function runTester(configLocation: string): Promise<void> {
    const usersConfigLocation = path.resolve(configLocation);

    if (!fs.existsSync(ESLINT_REMOTE_TESTER_BIN)) {
        throw new Error(
            `Missing eslint-remote-tester. Expected it to be available at ${path.resolve(
                ESLINT_REMOTE_TESTER_BIN
            )}`
        );
    }
    if (!fs.existsSync(usersConfigLocation)) {
        throw new Error(
            `Unable to find eslint-remote-tester config with path ${usersConfigLocation}`
        );
    }

    // Try-catch required by esbuild
    let usersConfig;
    // eslint-disable-next-line no-useless-catch
    try {
        usersConfig = require(usersConfigLocation);
    } catch (e) {
        throw e;
    }

    const config = {
        ...DEFAULT_CONFIG,
        ...usersConfig,
    };

    // Write eslint-remote-tester configuration file
    fs.writeFileSync(
        INTERNAL_CONFIG,
        CONFIGURATION_TEMPLATE(config, usersConfigLocation)
    );

    // Validate configuration before run
    const { validateConfig } = requirePeerDependency('eslint-remote-tester');
    await validateConfig(config, false);

    await exec(
        `${ESLINT_REMOTE_TESTER_BIN} --config ./${INTERNAL_CONFIG}`,
        [],
        {
            ignoreReturnCode: true,
            env: { ...process.env, NODE_OPTIONS: '--max_old_space_size=5120' },
        }
    );
}
