name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build
        run: |
          pnpm install
          pnpm build

      - name: Test
        run: pnpm test
