name: Update dist/index.js

on:
  push:
    branches:
      - master
jobs:
  build-and-update:
    runs-on: ubuntu-latest
    name: Update dist/index.js
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build
        run: |
          pnpm install
          pnpm prebuild
          pnpm build

      - name: Push updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(build): update dist/index.js'
